name: 📄 PDF Processing

on:
  push:
    branches:
      - main
      - development
    paths:
      - 'Annual Security Reports/**/*.pdf'
  workflow_dispatch:

jobs:
  dispatcher:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - name: ✅ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔍 Find new and modified PDF files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: "Annual Security Reports/**/*.pdf"
          separator: " "

  process-and-update:
    needs: dispatcher
    if: needs.dispatcher.outputs.files != ''
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJson(format('["{0}"]', join(split(needs.dispatcher.outputs.files, ' '), '","'))) }}
    
    steps:
      - name: ✅ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests google-api-python-client 'markitdown[pdf]' google-generativeai pyyaml mistune GitPython

      - name: 🛡️ VirusTotal Scan
        id: virus-total-scan
        env: # This job needs permissions to write to the repo
          VIRUS_TOTAL_API_KEY: ${{ secrets.VIRUS_TOTAL_API_KEY }}
        run: |
          echo "${{ matrix.file }}" > changed_files.txt
          python ./.github/scripts/virus-total-scan.py changed_files.txt

      - name: ⚙️ PDF to Markdown Conversion
        id: pdf-to-markdown
        if: steps.virus-total-scan.conclusion == 'success'
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GOOGLE_SEARCH_API_KEY: ${{ secrets.GOOGLE_SEARCH_API_KEY }}
          GOOGLE_CSE_ID: ${{ secrets.GOOGLE_CSE_ID }}
          CONVERTED_REPORTS_JSON_PATH: "converted_report.json"
        run: |
          python ./.github/scripts/pdf-converter.py "${{ matrix.file }}" ".github/ai-prompts/pdf-to-markdown-prompt.md" "v1.0" "${{ github.ref_name }}" "converted_report.json"

      - name: 📝 Update README
        id: update-readme
        if: steps.pdf-to-markdown.conclusion == 'success'
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          MD_FILE=$(jq -r '[0].output_path' converted_report.json)
          python3 ./.github/scripts/update-readme.py "$MD_FILE"

      - name: ⬆️ Commit and Push Changes
        if: steps.update-readme.conclusion == 'success'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "ℹ️ No changes to commit"
            exit 0
          fi
          git commit -m "docs: add new security report and update README"
          git push
